# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ael-kadh <ael-kadh@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/06/19 23:21:06 by ael-kadh          #+#    #+#              #
#    Updated: 2015/06/19 23:21:08 by ael-kadh         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RESULT = gardening
SOURCES = gardening.ml
LIBS = graphics
OCAMLMAKEFILE = OCamlMakefile
include $(OCAMLMAKEFILE)
