RESULT = molecule
SOURCES = atom.ml aluminium.ml beryllium.ml calcium.ml chlorine.ml helium.ml indium.ml lithium.ml nitrogen.ml phosphorus.ml silicon.ml sulfur.ml\
	argon.ml barium.ml boron.ml carbon.ml fluorine.ml hydrogen.ml krypton.ml magnesium.ml neon.ml oxygen.ml radium.ml sodium.ml molecule.ml water.ml\
	carbon_dioxyde.ml trinitrotoluene.ml chlorophylle_a.ml chlorophylle_b.ml chlorophylle_c1.ml chlorophylle_c2.ml chlorophylle_d.ml chlorophylle_f.ml main.ml
OCAMLMAKEFILE = OCamlMakefile
include $(OCAMLMAKEFILE)
