RESULT = atom
SOURCES = atom.ml aluminium.ml beryllium.ml calcium.ml chlorine.ml helium.ml indium.ml lithium.ml nitrogen.ml phosphorus.ml silicon.ml sulfur.ml\
	argon.ml barium.ml boron.ml carbon.ml fluorine.ml hydrogen.ml krypton.ml magnesium.ml neon.ml oxygen.ml radium.ml sodium.ml main.ml
OCAMLMAKEFILE = OCamlMakefile
include $(OCAMLMAKEFILE)
